# Generated by Django 6.0.2 on 2026-03-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.FileField(blank=True, null=True, upload_to='games/files/'),
        ),
    ]
